[project]
name = "capital-team"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.35.0",
    "duckdb>=1.0.0",
    "pandas>=2.0.0",
    "plotly>=5.20.0",
    "pyarrow>=14.0.0",
    "boto3>=1.34.0",
    "numpy>=1.26.0",
    "yfinance>=1.4.1",
    "python-dotenv>=1.2.2",
    "botocore[crt]>=1.43.18",
    "matplotlib>=3.10.9",
    "lseg-data>=2.0.0",
    "pyportfolioopt>=1.6.0",
]

[tool.setuptools]
packages = []
